### ISSUE TITLE
[feature request] Add option to hide arrows in explorer

### ISSUE THREAD

**Issue by Alecton4** [thang-nm/Catppuccin-Perfect-Icons#18]
It might be better to include a setting to optionally hide these arrows:

![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/43232804/35b73c0a-db0e-4c80-b53b-bf84bd968235)

For example, [Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme) offers `"material-icon-theme.hidesExplorerArrows": true` to hide the arrows.

**Comment by thang-nm** [comment]
@Alecton4 Currently I don't want to put any JS code in it, I just want to keep it simple.

**Comment by Alecton4** [comment]
@thang-nm Thanks that's reasonable. I found [the same issue on the upstream repository](https://github.com/catppuccin/vscode-icons/issues/3). So I guess we will have this functionality when the upstream adds it?

**Comment by thang-nm** [comment]
@Alecton4 I just created some [commands](https://github.com/thang-nm/Catppuccin-Perfect-Icons#%EF%B8%8F-customization) to customize, and I hope they work and you like them too.

**Comment by Alecton4** [comment]
@thang-nm Such brilliant work! Tested them all on VSCode 1.85.1 on openSUSE Tumbleweed 20231222 with node 16.20.2, and works perfectly!

**Comment by Alecton4** [comment]
@thang-nm Now the upstream also [added this feature](https://github.com/catppuccin/vscode-icons/issues/3#issuecomment-1913190229) as a settings option, maybe we can try integrating it :)

**Comment by thang-nm** [comment]
@Alecton4 You're right. I will plan to do it! 👍🏻
