### ISSUE TITLE
`folder_godot.svg` and `folder_godot__open.svg` should be reversed

### ISSUE THREAD

**Issue by Alecton4** [thang-nm/Catppuccin-Perfect-Icons#23]
Current close state:

![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/43232804/fd1405ad-495f-4c30-8280-8dd982947fdb)

Current open state:

![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/43232804/278f4ef5-659d-4935-b9b4-8603f3866484)

**Comment by thang-nm** [comment]
My bad. I will fix it soon! Thank you!

**Comment by Alecton4** [comment]
Verified already fixed in the new release.
