### ISSUE TITLE
Add some folder icons

### ISSUE THREAD

**Issue by LatenPath** [thang-nm/Catppuccin-Perfect-Icons#25]
There some folder i think we need icons for it.
![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/6e62be4c-d1ee-409c-8e98-2a48b95d0dfe)

Environments (.env), system, desktop, development, production, users,... is popular folders.
Scenes, camera, graphic, textures, vfx,... is use by Unity, C++ (Unreal) projects.
Chart, excel, cvs, text, colors,... is folder for specific resources.
Shortcut, Urls, Session,... is for related-API folder.

...Well, I think it maybe too much and some folder can use icon of it related-folder. Ex: "text" can use "font" folder icon,...
A feature like VsCode icon extension for setting folder/file use as same as icon of some has been set up folder/file in 'settings.json' will reduce the number of icon requests.

Anyway, thank you so much for this great extension. In my opinion, it more better than the origin one!

**Comment by thang-nm** [comment]
Thank you. I will consider your suggestion.
