### ISSUE TITLE
[new icon] Add support for `.lhs` file

### ISSUE THREAD

**Issue by Alecton4** [thang-nm/Catppuccin-Perfect-Icons#27]
This is [literate Haskell program](https://wiki.haskell.org/Literate_programming). Maybe we can just use the same icon as Haskell or use a different color.

**Comment by thang-nm** [comment]
Haskell seems lonely, so I'll use the same icon.

**Comment by thang-nm** [comment]
I just added it in the latest version.

**Comment by Alecton4** [comment]
Thanks! Verified to be working. 

But after some actual use, I think it might be better if `.hs` and `.lhs` have different colors... Personally I think the color of $\LaTeX$ would be good for `.lhs`. What do you think?

**Comment by thang-nm** [comment]
Yeah, I'll change it soon!

**Comment by thang-nm** [comment]
@Alecton4 You can check the latest version now 🎉. If you want any change, just let me know.

**Comment by Alecton4** [comment]
Looks fantastic!
