### ISSUE TITLE
Color of `.helmignore`

### ISSUE THREAD

**Issue by Alecton4** [thang-nm/Catppuccin-Perfect-Icons#31]
The current color is blue. Maybe make it the same (grey) as other "ignore" files (like `.dockerignore`)?

![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/43232804/89fe734a-4b6d-42c2-9924-b604fbaa3639)

![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/43232804/fc19d526-dc1d-4c6b-b98e-d25fd0ba9767)

**Comment by thang-nm** [comment]
You're right! I thought about it. What do you think if I use the blue one for [chart.yaml](https://helm.sh/docs/topics/charts/)?

**Comment by Alecton4** [comment]
@thang-nm I think using the blue one for `Chart.yaml` is worth trying! 

Initially I worried `Chart.yaml` might appear in some scenarios where they are not for Helm, but after [some investigations](https://github.com/search?q=path%3A**%2FChart.yaml&type=code), it seems that kind of scenario is rare.

**Comment by thang-nm** [comment]
I just added it to the latest release.
