### ISSUE TITLE
Icon for `rules` folder

### ISSUE THREAD

**Issue by LatenPath** [thang-nm/Catppuccin-Perfect-Icons#32]
Im working on `rules` folder which store `eslint rule`. Currently, `rules` folder still not have any icon, so there some icons i think will suit it:

![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/84a6477e-6027-4570-91f3-26375e53b041)

![rule-svg](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/7169e632-5882-4b77-b53e-99ffd39e4e76)

or this one:

![computer-icons-business-rule-icon-design-png-favpng-rMiE0MduGpDUvPEMC6Udy485W](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/5aac82ee-b4f6-4da8-967b-b9b381825e43)

Thank you so much! 💯 

p/s: can you conveniently match `environment/environments` folder with `.env` icon? They should bond together 😄 
![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/b943c477-7652-4c94-a343-5943b2679406)

**Comment by thang-nm** [comment]
Yeah, I'll update it soon!

**Comment by thang-nm** [comment]
@LatenPath It's hard to find an icon for the rule folder, because there isn't a specific one for it. So I made a clear and simple icon. I may update it to a better version if I find one.
And I think environment folder should use folder icon because it's a folder.

**Comment by LatenPath** [comment]
`And I think environment folder should use folder icon because it's a folder.`

I mean that because `environment` folder store `.env` files, so i think we can change the folder icon  to something like:
![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/d49726e8-9ee8-42a1-a4da-e62cb37aacf6)
But `.env` small icon in below instead of the red lock.

` So I made a clear and simple icon. `
Thank you so much, sir! 👍

**Comment by LatenPath** [comment]
![image](https://github.com/thang-nm/Catppuccin-Perfect-Icons/assets/145383056/3f64bb87-ff2f-4c6c-85a3-d5932f233847)

💯
